<expr> ::= <mapping> { "&" <mapping> }

<mapping> ::= [ <agents> ] { <selector> } { <array_selector> } [ "=" "$" { <selector> } { <array_selector> } ]

<agents> ::= "@" [ "@" { <atom> "@" } ]
    | <atom> "@" { <atom> "@" }

<selector> ::= "." NAME
    | "[" <atom> "]"
    | "[" [ SLICE ] "]"

<array_selector> ::= "(" <slices> ")"

<slices> ::= SLICE { "," SLICE }

<atom> ::= NAME | QUOTED_STRING

NAME ::= [A-Za-z_][A-Za-z0-9_]*

QUOTED_STRING ::= DOUBLE_QUOTED_STRING | SINGLE_QUOTED_STRING

SLICE ::= ^\s*((?'start'[+-]?\s*\d+)?\s*:\s*(?'stop'[+-]?\s*\d+)?\s*(:\s*(?'step'[+-]?\s*\d+)?)?|(?'index'[+-]?\s*\d+)|(?'ellipsis'\.\.\.)|(?'newaxis'(np\.)?newaxis))\s*$