// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: locator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gymize.Protobuf {

  /// <summary>Holder for reflection information generated from locator.proto</summary>
  public static partial class LocatorReflection {

    #region Descriptor
    /// <summary>File descriptor for locator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LocatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1sb2NhdG9yLnByb3RvIpgBCgpTbGljZVByb3RvEhEKCWhhc19zdGFydBgB",
            "IAEoCBINCgVzdGFydBgCIAEoBRIQCghoYXNfc3RvcBgDIAEoCBIMCgRzdG9w",
            "GAQgASgFEgwKBHN0ZXAYBSABKAUSEAoIaXNfaW5kZXgYBiABKAgSEwoLaXNf",
            "ZWxsaXBzaXMYByABKAgSEwoLaXNfbmV3X2F4aXMYCCABKAgiWwoNU2VsZWN0",
            "b3JQcm90bxIgCgR0eXBlGAEgASgOMhIuU2VsZWN0b3JUeXBlUHJvdG8SGwoG",
            "c2xpY2VzGAIgAygLMgsuU2xpY2VQcm90bxILCgNrZXkYAyABKAkiiwEKDE1h",
            "cHBpbmdQcm90bxIVCg1pc19hbGxfYWdlbnRzGAEgASgIEg4KBmFnZW50cxgC",
            "IAMoCRIPCgdpc19yb290GAMgASgIEiMKC2Rlc3RpbmF0aW9uGAQgAygLMg4u",
            "U2VsZWN0b3JQcm90bxIeCgZzb3VyY2UYBSADKAsyDi5TZWxlY3RvclByb3Rv",
            "Ii8KDExvY2F0b3JQcm90bxIfCghtYXBwaW5ncxgBIAMoCzINLk1hcHBpbmdQ",
            "cm90byq3AQoRU2VsZWN0b3JUeXBlUHJvdG8SIwofU0VMRUNUT1JfVFlQRV9Q",
            "Uk9UT19VTlNQRUNJRklFRBAAEhwKGFNFTEVDVE9SX1RZUEVfUFJPVE9fRElD",
            "VBABEh0KGVNFTEVDVE9SX1RZUEVfUFJPVE9fVFVQTEUQAhIgChxTRUxFQ1RP",
            "Ul9UWVBFX1BST1RPX1NFUVVFTkNFEAMSHgoaU0VMRUNUT1JfVFlQRV9QUk9U",
            "T19URU5TT1IQBEISqgIPR3ltaXplLlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Gymize.Protobuf.SelectorTypeProto), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Gymize.Protobuf.SliceProto), global::Gymize.Protobuf.SliceProto.Parser, new[]{ "HasStart", "Start", "HasStop", "Stop", "Step", "IsIndex", "IsEllipsis", "IsNewAxis" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gymize.Protobuf.SelectorProto), global::Gymize.Protobuf.SelectorProto.Parser, new[]{ "Type", "Slices", "Key" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gymize.Protobuf.MappingProto), global::Gymize.Protobuf.MappingProto.Parser, new[]{ "IsAllAgents", "Agents", "IsRoot", "Destination", "Source" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gymize.Protobuf.LocatorProto), global::Gymize.Protobuf.LocatorProto.Parser, new[]{ "Mappings" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum SelectorTypeProto {
    [pbr::OriginalName("SELECTOR_TYPE_PROTO_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("SELECTOR_TYPE_PROTO_DICT")] Dict = 1,
    [pbr::OriginalName("SELECTOR_TYPE_PROTO_TUPLE")] Tuple = 2,
    [pbr::OriginalName("SELECTOR_TYPE_PROTO_SEQUENCE")] Sequence = 3,
    [pbr::OriginalName("SELECTOR_TYPE_PROTO_TENSOR")] Tensor = 4,
  }

  #endregion

  #region Messages
  public sealed partial class SliceProto : pb::IMessage<SliceProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SliceProto> _parser = new pb::MessageParser<SliceProto>(() => new SliceProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SliceProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gymize.Protobuf.LocatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SliceProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SliceProto(SliceProto other) : this() {
      hasStart_ = other.hasStart_;
      start_ = other.start_;
      hasStop_ = other.hasStop_;
      stop_ = other.stop_;
      step_ = other.step_;
      isIndex_ = other.isIndex_;
      isEllipsis_ = other.isEllipsis_;
      isNewAxis_ = other.isNewAxis_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SliceProto Clone() {
      return new SliceProto(this);
    }

    /// <summary>Field number for the "has_start" field.</summary>
    public const int HasStartFieldNumber = 1;
    private bool hasStart_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStart {
      get { return hasStart_; }
      set {
        hasStart_ = value;
      }
    }

    /// <summary>Field number for the "start" field.</summary>
    public const int StartFieldNumber = 2;
    private int start_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Start {
      get { return start_; }
      set {
        start_ = value;
      }
    }

    /// <summary>Field number for the "has_stop" field.</summary>
    public const int HasStopFieldNumber = 3;
    private bool hasStop_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStop {
      get { return hasStop_; }
      set {
        hasStop_ = value;
      }
    }

    /// <summary>Field number for the "stop" field.</summary>
    public const int StopFieldNumber = 4;
    private int stop_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Stop {
      get { return stop_; }
      set {
        stop_ = value;
      }
    }

    /// <summary>Field number for the "step" field.</summary>
    public const int StepFieldNumber = 5;
    private int step_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Step {
      get { return step_; }
      set {
        step_ = value;
      }
    }

    /// <summary>Field number for the "is_index" field.</summary>
    public const int IsIndexFieldNumber = 6;
    private bool isIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsIndex {
      get { return isIndex_; }
      set {
        isIndex_ = value;
      }
    }

    /// <summary>Field number for the "is_ellipsis" field.</summary>
    public const int IsEllipsisFieldNumber = 7;
    private bool isEllipsis_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsEllipsis {
      get { return isEllipsis_; }
      set {
        isEllipsis_ = value;
      }
    }

    /// <summary>Field number for the "is_new_axis" field.</summary>
    public const int IsNewAxisFieldNumber = 8;
    private bool isNewAxis_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsNewAxis {
      get { return isNewAxis_; }
      set {
        isNewAxis_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SliceProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SliceProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HasStart != other.HasStart) return false;
      if (Start != other.Start) return false;
      if (HasStop != other.HasStop) return false;
      if (Stop != other.Stop) return false;
      if (Step != other.Step) return false;
      if (IsIndex != other.IsIndex) return false;
      if (IsEllipsis != other.IsEllipsis) return false;
      if (IsNewAxis != other.IsNewAxis) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasStart != false) hash ^= HasStart.GetHashCode();
      if (Start != 0) hash ^= Start.GetHashCode();
      if (HasStop != false) hash ^= HasStop.GetHashCode();
      if (Stop != 0) hash ^= Stop.GetHashCode();
      if (Step != 0) hash ^= Step.GetHashCode();
      if (IsIndex != false) hash ^= IsIndex.GetHashCode();
      if (IsEllipsis != false) hash ^= IsEllipsis.GetHashCode();
      if (IsNewAxis != false) hash ^= IsNewAxis.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasStart != false) {
        output.WriteRawTag(8);
        output.WriteBool(HasStart);
      }
      if (Start != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Start);
      }
      if (HasStop != false) {
        output.WriteRawTag(24);
        output.WriteBool(HasStop);
      }
      if (Stop != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Stop);
      }
      if (Step != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Step);
      }
      if (IsIndex != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsIndex);
      }
      if (IsEllipsis != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsEllipsis);
      }
      if (IsNewAxis != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsNewAxis);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasStart != false) {
        output.WriteRawTag(8);
        output.WriteBool(HasStart);
      }
      if (Start != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Start);
      }
      if (HasStop != false) {
        output.WriteRawTag(24);
        output.WriteBool(HasStop);
      }
      if (Stop != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Stop);
      }
      if (Step != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Step);
      }
      if (IsIndex != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsIndex);
      }
      if (IsEllipsis != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsEllipsis);
      }
      if (IsNewAxis != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsNewAxis);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasStart != false) {
        size += 1 + 1;
      }
      if (Start != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Start);
      }
      if (HasStop != false) {
        size += 1 + 1;
      }
      if (Stop != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Stop);
      }
      if (Step != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Step);
      }
      if (IsIndex != false) {
        size += 1 + 1;
      }
      if (IsEllipsis != false) {
        size += 1 + 1;
      }
      if (IsNewAxis != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SliceProto other) {
      if (other == null) {
        return;
      }
      if (other.HasStart != false) {
        HasStart = other.HasStart;
      }
      if (other.Start != 0) {
        Start = other.Start;
      }
      if (other.HasStop != false) {
        HasStop = other.HasStop;
      }
      if (other.Stop != 0) {
        Stop = other.Stop;
      }
      if (other.Step != 0) {
        Step = other.Step;
      }
      if (other.IsIndex != false) {
        IsIndex = other.IsIndex;
      }
      if (other.IsEllipsis != false) {
        IsEllipsis = other.IsEllipsis;
      }
      if (other.IsNewAxis != false) {
        IsNewAxis = other.IsNewAxis;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            HasStart = input.ReadBool();
            break;
          }
          case 16: {
            Start = input.ReadInt32();
            break;
          }
          case 24: {
            HasStop = input.ReadBool();
            break;
          }
          case 32: {
            Stop = input.ReadInt32();
            break;
          }
          case 40: {
            Step = input.ReadInt32();
            break;
          }
          case 48: {
            IsIndex = input.ReadBool();
            break;
          }
          case 56: {
            IsEllipsis = input.ReadBool();
            break;
          }
          case 64: {
            IsNewAxis = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            HasStart = input.ReadBool();
            break;
          }
          case 16: {
            Start = input.ReadInt32();
            break;
          }
          case 24: {
            HasStop = input.ReadBool();
            break;
          }
          case 32: {
            Stop = input.ReadInt32();
            break;
          }
          case 40: {
            Step = input.ReadInt32();
            break;
          }
          case 48: {
            IsIndex = input.ReadBool();
            break;
          }
          case 56: {
            IsEllipsis = input.ReadBool();
            break;
          }
          case 64: {
            IsNewAxis = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SelectorProto : pb::IMessage<SelectorProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SelectorProto> _parser = new pb::MessageParser<SelectorProto>(() => new SelectorProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SelectorProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gymize.Protobuf.LocatorReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectorProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectorProto(SelectorProto other) : this() {
      type_ = other.type_;
      slices_ = other.slices_.Clone();
      key_ = other.key_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectorProto Clone() {
      return new SelectorProto(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Gymize.Protobuf.SelectorTypeProto type_ = global::Gymize.Protobuf.SelectorTypeProto.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Gymize.Protobuf.SelectorTypeProto Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "slices" field.</summary>
    public const int SlicesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Gymize.Protobuf.SliceProto> _repeated_slices_codec
        = pb::FieldCodec.ForMessage(18, global::Gymize.Protobuf.SliceProto.Parser);
    private readonly pbc::RepeatedField<global::Gymize.Protobuf.SliceProto> slices_ = new pbc::RepeatedField<global::Gymize.Protobuf.SliceProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Gymize.Protobuf.SliceProto> Slices {
      get { return slices_; }
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 3;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SelectorProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SelectorProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if(!slices_.Equals(other.slices_)) return false;
      if (Key != other.Key) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Gymize.Protobuf.SelectorTypeProto.Unspecified) hash ^= Type.GetHashCode();
      hash ^= slices_.GetHashCode();
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Gymize.Protobuf.SelectorTypeProto.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      slices_.WriteTo(output, _repeated_slices_codec);
      if (Key.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Key);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Gymize.Protobuf.SelectorTypeProto.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      slices_.WriteTo(ref output, _repeated_slices_codec);
      if (Key.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Key);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Gymize.Protobuf.SelectorTypeProto.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      size += slices_.CalculateSize(_repeated_slices_codec);
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SelectorProto other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Gymize.Protobuf.SelectorTypeProto.Unspecified) {
        Type = other.Type;
      }
      slices_.Add(other.slices_);
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Gymize.Protobuf.SelectorTypeProto) input.ReadEnum();
            break;
          }
          case 18: {
            slices_.AddEntriesFrom(input, _repeated_slices_codec);
            break;
          }
          case 26: {
            Key = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Gymize.Protobuf.SelectorTypeProto) input.ReadEnum();
            break;
          }
          case 18: {
            slices_.AddEntriesFrom(ref input, _repeated_slices_codec);
            break;
          }
          case 26: {
            Key = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MappingProto : pb::IMessage<MappingProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MappingProto> _parser = new pb::MessageParser<MappingProto>(() => new MappingProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MappingProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gymize.Protobuf.LocatorReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MappingProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MappingProto(MappingProto other) : this() {
      isAllAgents_ = other.isAllAgents_;
      agents_ = other.agents_.Clone();
      isRoot_ = other.isRoot_;
      destination_ = other.destination_.Clone();
      source_ = other.source_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MappingProto Clone() {
      return new MappingProto(this);
    }

    /// <summary>Field number for the "is_all_agents" field.</summary>
    public const int IsAllAgentsFieldNumber = 1;
    private bool isAllAgents_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAllAgents {
      get { return isAllAgents_; }
      set {
        isAllAgents_ = value;
      }
    }

    /// <summary>Field number for the "agents" field.</summary>
    public const int AgentsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_agents_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> agents_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// If is_all_agents == true, then this is the list of unavalible agents
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Agents {
      get { return agents_; }
    }

    /// <summary>Field number for the "is_root" field.</summary>
    public const int IsRootFieldNumber = 3;
    private bool isRoot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRoot {
      get { return isRoot_; }
      set {
        isRoot_ = value;
      }
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Gymize.Protobuf.SelectorProto> _repeated_destination_codec
        = pb::FieldCodec.ForMessage(34, global::Gymize.Protobuf.SelectorProto.Parser);
    private readonly pbc::RepeatedField<global::Gymize.Protobuf.SelectorProto> destination_ = new pbc::RepeatedField<global::Gymize.Protobuf.SelectorProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Gymize.Protobuf.SelectorProto> Destination {
      get { return destination_; }
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Gymize.Protobuf.SelectorProto> _repeated_source_codec
        = pb::FieldCodec.ForMessage(42, global::Gymize.Protobuf.SelectorProto.Parser);
    private readonly pbc::RepeatedField<global::Gymize.Protobuf.SelectorProto> source_ = new pbc::RepeatedField<global::Gymize.Protobuf.SelectorProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Gymize.Protobuf.SelectorProto> Source {
      get { return source_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MappingProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MappingProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsAllAgents != other.IsAllAgents) return false;
      if(!agents_.Equals(other.agents_)) return false;
      if (IsRoot != other.IsRoot) return false;
      if(!destination_.Equals(other.destination_)) return false;
      if(!source_.Equals(other.source_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsAllAgents != false) hash ^= IsAllAgents.GetHashCode();
      hash ^= agents_.GetHashCode();
      if (IsRoot != false) hash ^= IsRoot.GetHashCode();
      hash ^= destination_.GetHashCode();
      hash ^= source_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IsAllAgents != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsAllAgents);
      }
      agents_.WriteTo(output, _repeated_agents_codec);
      if (IsRoot != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsRoot);
      }
      destination_.WriteTo(output, _repeated_destination_codec);
      source_.WriteTo(output, _repeated_source_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IsAllAgents != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsAllAgents);
      }
      agents_.WriteTo(ref output, _repeated_agents_codec);
      if (IsRoot != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsRoot);
      }
      destination_.WriteTo(ref output, _repeated_destination_codec);
      source_.WriteTo(ref output, _repeated_source_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsAllAgents != false) {
        size += 1 + 1;
      }
      size += agents_.CalculateSize(_repeated_agents_codec);
      if (IsRoot != false) {
        size += 1 + 1;
      }
      size += destination_.CalculateSize(_repeated_destination_codec);
      size += source_.CalculateSize(_repeated_source_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MappingProto other) {
      if (other == null) {
        return;
      }
      if (other.IsAllAgents != false) {
        IsAllAgents = other.IsAllAgents;
      }
      agents_.Add(other.agents_);
      if (other.IsRoot != false) {
        IsRoot = other.IsRoot;
      }
      destination_.Add(other.destination_);
      source_.Add(other.source_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsAllAgents = input.ReadBool();
            break;
          }
          case 18: {
            agents_.AddEntriesFrom(input, _repeated_agents_codec);
            break;
          }
          case 24: {
            IsRoot = input.ReadBool();
            break;
          }
          case 34: {
            destination_.AddEntriesFrom(input, _repeated_destination_codec);
            break;
          }
          case 42: {
            source_.AddEntriesFrom(input, _repeated_source_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IsAllAgents = input.ReadBool();
            break;
          }
          case 18: {
            agents_.AddEntriesFrom(ref input, _repeated_agents_codec);
            break;
          }
          case 24: {
            IsRoot = input.ReadBool();
            break;
          }
          case 34: {
            destination_.AddEntriesFrom(ref input, _repeated_destination_codec);
            break;
          }
          case 42: {
            source_.AddEntriesFrom(ref input, _repeated_source_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LocatorProto : pb::IMessage<LocatorProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LocatorProto> _parser = new pb::MessageParser<LocatorProto>(() => new LocatorProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LocatorProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gymize.Protobuf.LocatorReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocatorProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocatorProto(LocatorProto other) : this() {
      mappings_ = other.mappings_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocatorProto Clone() {
      return new LocatorProto(this);
    }

    /// <summary>Field number for the "mappings" field.</summary>
    public const int MappingsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Gymize.Protobuf.MappingProto> _repeated_mappings_codec
        = pb::FieldCodec.ForMessage(10, global::Gymize.Protobuf.MappingProto.Parser);
    private readonly pbc::RepeatedField<global::Gymize.Protobuf.MappingProto> mappings_ = new pbc::RepeatedField<global::Gymize.Protobuf.MappingProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Gymize.Protobuf.MappingProto> Mappings {
      get { return mappings_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LocatorProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LocatorProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!mappings_.Equals(other.mappings_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= mappings_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      mappings_.WriteTo(output, _repeated_mappings_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      mappings_.WriteTo(ref output, _repeated_mappings_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += mappings_.CalculateSize(_repeated_mappings_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LocatorProto other) {
      if (other == null) {
        return;
      }
      mappings_.Add(other.mappings_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            mappings_.AddEntriesFrom(input, _repeated_mappings_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            mappings_.AddEntriesFrom(ref input, _repeated_mappings_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
