// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: signaling.proto

public final class Signaling {
  private Signaling() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code SignalType}
   */
  public enum SignalType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SIGNAL_TYPE_UNSPECIFIED = 0;</code>
     */
    SIGNAL_TYPE_UNSPECIFIED(0),
    /**
     * <code>SIGNAL_TYPE_INIT = 1;</code>
     */
    SIGNAL_TYPE_INIT(1),
    /**
     * <pre>
     * update the peer server information
     * </pre>
     *
     * <code>SIGNAL_TYPE_UPDATE = 2;</code>
     */
    SIGNAL_TYPE_UPDATE(2),
    /**
     * <pre>
     * resume the connection with same signal id
     * </pre>
     *
     * <code>SIGNAL_TYPE_RESUME = 3;</code>
     */
    SIGNAL_TYPE_RESUME(3),
    /**
     * <pre>
     * ask another peer to close, and remove signal id
     * </pre>
     *
     * <code>SIGNAL_TYPE_CLOSE = 4;</code>
     */
    SIGNAL_TYPE_CLOSE(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SIGNAL_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int SIGNAL_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>SIGNAL_TYPE_INIT = 1;</code>
     */
    public static final int SIGNAL_TYPE_INIT_VALUE = 1;
    /**
     * <pre>
     * update the peer server information
     * </pre>
     *
     * <code>SIGNAL_TYPE_UPDATE = 2;</code>
     */
    public static final int SIGNAL_TYPE_UPDATE_VALUE = 2;
    /**
     * <pre>
     * resume the connection with same signal id
     * </pre>
     *
     * <code>SIGNAL_TYPE_RESUME = 3;</code>
     */
    public static final int SIGNAL_TYPE_RESUME_VALUE = 3;
    /**
     * <pre>
     * ask another peer to close, and remove signal id
     * </pre>
     *
     * <code>SIGNAL_TYPE_CLOSE = 4;</code>
     */
    public static final int SIGNAL_TYPE_CLOSE_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SignalType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SignalType forNumber(int value) {
      switch (value) {
        case 0: return SIGNAL_TYPE_UNSPECIFIED;
        case 1: return SIGNAL_TYPE_INIT;
        case 2: return SIGNAL_TYPE_UPDATE;
        case 3: return SIGNAL_TYPE_RESUME;
        case 4: return SIGNAL_TYPE_CLOSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SignalType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SignalType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SignalType>() {
            public SignalType findValueByNumber(int number) {
              return SignalType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Signaling.getDescriptor().getEnumTypes().get(0);
    }

    private static final SignalType[] VALUES = values();

    public static SignalType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SignalType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SignalType)
  }

  /**
   * Protobuf enum {@code PeerType}
   */
  public enum PeerType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PEER_TYPE_UNSPECIFIED = 0;</code>
     */
    PEER_TYPE_UNSPECIFIED(0),
    /**
     * <code>PEER_TYPE_ACTIVE = 1;</code>
     */
    PEER_TYPE_ACTIVE(1),
    /**
     * <code>PEER_TYPE_PASSIVE = 2;</code>
     */
    PEER_TYPE_PASSIVE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PEER_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int PEER_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>PEER_TYPE_ACTIVE = 1;</code>
     */
    public static final int PEER_TYPE_ACTIVE_VALUE = 1;
    /**
     * <code>PEER_TYPE_PASSIVE = 2;</code>
     */
    public static final int PEER_TYPE_PASSIVE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PeerType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PeerType forNumber(int value) {
      switch (value) {
        case 0: return PEER_TYPE_UNSPECIFIED;
        case 1: return PEER_TYPE_ACTIVE;
        case 2: return PEER_TYPE_PASSIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PeerType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PeerType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PeerType>() {
            public PeerType findValueByNumber(int number) {
              return PeerType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Signaling.getDescriptor().getEnumTypes().get(1);
    }

    private static final PeerType[] VALUES = values();

    public static PeerType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PeerType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PeerType)
  }

  public interface SignalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Signal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.SignalType signal_type = 1;</code>
     * @return The enum numeric value on the wire for signalType.
     */
    int getSignalTypeValue();
    /**
     * <code>.SignalType signal_type = 1;</code>
     * @return The signalType.
     */
    Signaling.SignalType getSignalType();

    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.PeerType peer_type = 5;</code>
     * @return The enum numeric value on the wire for peerType.
     */
    int getPeerTypeValue();
    /**
     * <code>.PeerType peer_type = 5;</code>
     * @return The peerType.
     */
    Signaling.PeerType getPeerType();

    /**
     * <code>string url = 6;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <code>string url = 6;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();
  }
  /**
   * Protobuf type {@code Signal}
   */
  public static final class Signal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Signal)
      SignalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Signal.newBuilder() to construct.
    private Signal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Signal() {
      signalType_ = 0;
      id_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
      peerType_ = 0;
      url_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Signal();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Signal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              signalType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              peerType_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Signaling.internal_static_Signal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Signaling.internal_static_Signal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Signaling.Signal.class, Signaling.Signal.Builder.class);
    }

    public static final int SIGNAL_TYPE_FIELD_NUMBER = 1;
    private int signalType_;
    /**
     * <code>.SignalType signal_type = 1;</code>
     * @return The enum numeric value on the wire for signalType.
     */
    @java.lang.Override public int getSignalTypeValue() {
      return signalType_;
    }
    /**
     * <code>.SignalType signal_type = 1;</code>
     * @return The signalType.
     */
    @java.lang.Override public Signaling.SignalType getSignalType() {
      @SuppressWarnings("deprecation")
      Signaling.SignalType result = Signaling.SignalType.valueOf(signalType_);
      return result == null ? Signaling.SignalType.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PEER_TYPE_FIELD_NUMBER = 5;
    private int peerType_;
    /**
     * <code>.PeerType peer_type = 5;</code>
     * @return The enum numeric value on the wire for peerType.
     */
    @java.lang.Override public int getPeerTypeValue() {
      return peerType_;
    }
    /**
     * <code>.PeerType peer_type = 5;</code>
     * @return The peerType.
     */
    @java.lang.Override public Signaling.PeerType getPeerType() {
      @SuppressWarnings("deprecation")
      Signaling.PeerType result = Signaling.PeerType.valueOf(peerType_);
      return result == null ? Signaling.PeerType.UNRECOGNIZED : result;
    }

    public static final int URL_FIELD_NUMBER = 6;
    private volatile java.lang.Object url_;
    /**
     * <code>string url = 6;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 6;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (signalType_ != Signaling.SignalType.SIGNAL_TYPE_UNSPECIFIED.getNumber()) {
        output.writeEnum(1, signalType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      if (peerType_ != Signaling.PeerType.PEER_TYPE_UNSPECIFIED.getNumber()) {
        output.writeEnum(5, peerType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(url_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, url_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (signalType_ != Signaling.SignalType.SIGNAL_TYPE_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, signalType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      if (peerType_ != Signaling.PeerType.PEER_TYPE_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, peerType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(url_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, url_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Signaling.Signal)) {
        return super.equals(obj);
      }
      Signaling.Signal other = (Signaling.Signal) obj;

      if (signalType_ != other.signalType_) return false;
      if (!getId()
          .equals(other.getId())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (peerType_ != other.peerType_) return false;
      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIGNAL_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + signalType_;
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PEER_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + peerType_;
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Signaling.Signal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Signaling.Signal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Signaling.Signal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Signaling.Signal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Signaling.Signal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Signaling.Signal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Signaling.Signal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Signaling.Signal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Signaling.Signal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Signaling.Signal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Signaling.Signal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Signaling.Signal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Signaling.Signal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Signal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Signal)
        Signaling.SignalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Signaling.internal_static_Signal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Signaling.internal_static_Signal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Signaling.Signal.class, Signaling.Signal.Builder.class);
      }

      // Construct using Signaling.Signal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        signalType_ = 0;

        id_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        name_ = "";

        peerType_ = 0;

        url_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Signaling.internal_static_Signal_descriptor;
      }

      @java.lang.Override
      public Signaling.Signal getDefaultInstanceForType() {
        return Signaling.Signal.getDefaultInstance();
      }

      @java.lang.Override
      public Signaling.Signal build() {
        Signaling.Signal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Signaling.Signal buildPartial() {
        Signaling.Signal result = new Signaling.Signal(this);
        result.signalType_ = signalType_;
        result.id_ = id_;
        result.data_ = data_;
        result.name_ = name_;
        result.peerType_ = peerType_;
        result.url_ = url_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Signaling.Signal) {
          return mergeFrom((Signaling.Signal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Signaling.Signal other) {
        if (other == Signaling.Signal.getDefaultInstance()) return this;
        if (other.signalType_ != 0) {
          setSignalTypeValue(other.getSignalTypeValue());
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.peerType_ != 0) {
          setPeerTypeValue(other.getPeerTypeValue());
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Signaling.Signal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Signaling.Signal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int signalType_ = 0;
      /**
       * <code>.SignalType signal_type = 1;</code>
       * @return The enum numeric value on the wire for signalType.
       */
      @java.lang.Override public int getSignalTypeValue() {
        return signalType_;
      }
      /**
       * <code>.SignalType signal_type = 1;</code>
       * @param value The enum numeric value on the wire for signalType to set.
       * @return This builder for chaining.
       */
      public Builder setSignalTypeValue(int value) {
        
        signalType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.SignalType signal_type = 1;</code>
       * @return The signalType.
       */
      @java.lang.Override
      public Signaling.SignalType getSignalType() {
        @SuppressWarnings("deprecation")
        Signaling.SignalType result = Signaling.SignalType.valueOf(signalType_);
        return result == null ? Signaling.SignalType.UNRECOGNIZED : result;
      }
      /**
       * <code>.SignalType signal_type = 1;</code>
       * @param value The signalType to set.
       * @return This builder for chaining.
       */
      public Builder setSignalType(Signaling.SignalType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        signalType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.SignalType signal_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignalType() {
        
        signalType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 2;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 4;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int peerType_ = 0;
      /**
       * <code>.PeerType peer_type = 5;</code>
       * @return The enum numeric value on the wire for peerType.
       */
      @java.lang.Override public int getPeerTypeValue() {
        return peerType_;
      }
      /**
       * <code>.PeerType peer_type = 5;</code>
       * @param value The enum numeric value on the wire for peerType to set.
       * @return This builder for chaining.
       */
      public Builder setPeerTypeValue(int value) {
        
        peerType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.PeerType peer_type = 5;</code>
       * @return The peerType.
       */
      @java.lang.Override
      public Signaling.PeerType getPeerType() {
        @SuppressWarnings("deprecation")
        Signaling.PeerType result = Signaling.PeerType.valueOf(peerType_);
        return result == null ? Signaling.PeerType.UNRECOGNIZED : result;
      }
      /**
       * <code>.PeerType peer_type = 5;</code>
       * @param value The peerType to set.
       * @return This builder for chaining.
       */
      public Builder setPeerType(Signaling.PeerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        peerType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.PeerType peer_type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPeerType() {
        
        peerType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>string url = 6;</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string url = 6;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 6;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 6;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Signal)
    }

    // @@protoc_insertion_point(class_scope:Signal)
    private static final Signaling.Signal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Signaling.Signal();
    }

    public static Signaling.Signal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Signal>
        PARSER = new com.google.protobuf.AbstractParser<Signal>() {
      @java.lang.Override
      public Signal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Signal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Signal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Signal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Signaling.Signal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Signal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Signal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017signaling.proto\"}\n\006Signal\022 \n\013signal_ty" +
      "pe\030\001 \001(\0162\013.SignalType\022\n\n\002id\030\002 \001(\t\022\014\n\004dat" +
      "a\030\003 \001(\014\022\014\n\004name\030\004 \001(\t\022\034\n\tpeer_type\030\005 \001(\016" +
      "2\t.PeerType\022\013\n\003url\030\006 \001(\t*\206\001\n\nSignalType\022" +
      "\033\n\027SIGNAL_TYPE_UNSPECIFIED\020\000\022\024\n\020SIGNAL_T" +
      "YPE_INIT\020\001\022\026\n\022SIGNAL_TYPE_UPDATE\020\002\022\026\n\022SI" +
      "GNAL_TYPE_RESUME\020\003\022\025\n\021SIGNAL_TYPE_CLOSE\020" +
      "\004*R\n\010PeerType\022\031\n\025PEER_TYPE_UNSPECIFIED\020\000" +
      "\022\024\n\020PEER_TYPE_ACTIVE\020\001\022\025\n\021PEER_TYPE_PASS" +
      "IVE\020\002B\030\252\002\025PAIA.Gymize.Signalingb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Signal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Signal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Signal_descriptor,
        new java.lang.String[] { "SignalType", "Id", "Data", "Name", "PeerType", "Url", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
