// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recording.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AudioFrameProto;
@class ImageFrameProto;
@class InstanceProto;
@class VideoProto;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RecordingRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface RecordingRoot : GPBRootObject
@end

#pragma mark - ImageFrameProto

typedef GPB_ENUM(ImageFrameProto_FieldNumber) {
  ImageFrameProto_FieldNumber_Image = 1,
  ImageFrameProto_FieldNumber_Duration = 2,
};

GPB_FINAL @interface ImageFrameProto : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) InstanceProto *image;
/** Test to see if @c image has been set. */
@property(nonatomic, readwrite) BOOL hasImage;

@property(nonatomic, readwrite) float duration;

@end

#pragma mark - AudioFrameProto

typedef GPB_ENUM(AudioFrameProto_FieldNumber) {
  AudioFrameProto_FieldNumber_Data_p = 1,
  AudioFrameProto_FieldNumber_Duration = 2,
};

GPB_FINAL @interface AudioFrameProto : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) InstanceProto *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite) float duration;

@end

#pragma mark - VideoProto

typedef GPB_ENUM(VideoProto_FieldNumber) {
  VideoProto_FieldNumber_ImagesArray = 1,
  VideoProto_FieldNumber_AudiosArray = 2,
};

GPB_FINAL @interface VideoProto : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ImageFrameProto*> *imagesArray;
/** The number of items in @c imagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AudioFrameProto*> *audiosArray;
/** The number of items in @c audiosArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger audiosArray_Count;

@end

#pragma mark - RecordingProto

typedef GPB_ENUM(RecordingProto_FieldNumber) {
  RecordingProto_FieldNumber_RenderMode = 1,
  RecordingProto_FieldNumber_Video = 2,
};

GPB_FINAL @interface RecordingProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *renderMode;

@property(nonatomic, readwrite, strong, null_resettable) VideoProto *video;
/** Test to see if @c video has been set. */
@property(nonatomic, readwrite) BOOL hasVideo;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
