# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("locator.proto", :syntax => :proto3) do
    add_message "SliceProto" do
      optional :has_start, :bool, 1
      optional :start, :int32, 2
      optional :has_stop, :bool, 3
      optional :stop, :int32, 4
      optional :step, :int32, 5
      optional :is_index, :bool, 6
      optional :is_ellipsis, :bool, 7
      optional :is_new_axis, :bool, 8
    end
    add_message "SelectorProto" do
      optional :type, :enum, 1, "SelectorTypeProto"
      repeated :slices, :message, 2, "SliceProto"
      optional :key, :string, 3
    end
    add_message "MappingProto" do
      optional :is_all_agents, :bool, 1
      repeated :agents, :string, 2
      optional :is_root, :bool, 3
      repeated :destination, :message, 4, "SelectorProto"
      repeated :source, :message, 5, "SelectorProto"
    end
    add_message "LocatorProto" do
      repeated :mappings, :message, 1, "MappingProto"
    end
    add_enum "SelectorTypeProto" do
      value :SELECTOR_TYPE_PROTO_UNSPECIFIED, 0
      value :SELECTOR_TYPE_PROTO_DICT, 1
      value :SELECTOR_TYPE_PROTO_TUPLE, 2
      value :SELECTOR_TYPE_PROTO_SEQUENCE, 3
      value :SELECTOR_TYPE_PROTO_TENSOR, 4
    end
  end
end

SliceProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SliceProto").msgclass
SelectorProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SelectorProto").msgclass
MappingProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MappingProto").msgclass
LocatorProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LocatorProto").msgclass
SelectorTypeProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SelectorTypeProto").enummodule
