# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: space.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("space.proto", :syntax => :proto3) do
    add_message "FloatTensor" do
      repeated :shape, :int32, 1
      repeated :array, :float, 2
    end
    add_message "IntTensor" do
      repeated :shape, :int32, 1
      repeated :array, :int32, 2
    end
    add_message "BoolTensor" do
      repeated :shape, :int32, 1
      repeated :array, :bool, 2
    end
    add_message "GraphSpace" do
      optional :node_space, :message, 1, "Space"
      optional :edge_space, :message, 2, "Space"
    end
    add_message "Graph" do
      optional :nodes, :message, 1, "FloatTensor"
      optional :edges, :message, 2, "FloatTensor"
      optional :edge_links, :message, 3, "IntTensor"
    end
    add_message "Image" do
      optional :compression_type, :enum, 1, "CompressionType"
      optional :data, :bytes, 2
      repeated :shape, :int32, 3
      repeated :dimension_mapping, :int32, 4
    end
    add_message "Space" do
      optional :space_type, :enum, 1, "SpaceType"
      repeated :shape, :int32, 2
      optional :data_type, :enum, 3, "DataType"
      repeated :low, :float, 4
      repeated :high, :float, 5
      optional :min, :int32, 6
      optional :max, :int32, 7
      repeated :nvec, :int32, 8
      repeated :charset, :string, 9
      map :dict_space, :string, :message, 10, "Space"
      map :list_space, :int32, :message, 11, "Space"
      optional :graph_space, :message, 12, "GraphSpace"
    end
    add_message "Data" do
      optional :space_type, :enum, 1, "SpaceType"
      optional :box, :message, 2, "FloatTensor"
      optional :discrete, :int32, 3
      optional :multi_binary, :message, 4, "BoolTensor"
      optional :multi_discrete, :message, 5, "IntTensor"
      optional :text, :string, 6
      map :dict, :string, :message, 7, "Data"
      map :list, :int32, :message, 8, "Data"
      optional :graph, :message, 9, "Graph"
      optional :image, :message, 10, "Image"
    end
    add_enum "CompressionType" do
      value :COMPRESSION_TYPE_UNSPECIFIED, 0
      value :COMPRESSION_TYPE_NONE, 1
      value :COMPRESSION_TYPE_PNG, 2
      value :COMPRESSION_TYPE_JPG, 3
    end
    add_enum "SpaceType" do
      value :SPACE_TYPE_UNSPECIFIED, 0
      value :SPACE_TYPE_BOX, 1
      value :SPACE_TYPE_DISCRETE, 2
      value :SPACE_TYPE_MULTI_BINARY, 3
      value :SPACE_TYPE_MULTI_DISCRETE, 4
      value :SPACE_TYPE_TEXT, 5
      value :SPACE_TYPE_DICT, 6
      value :SPACE_TYPE_TUPLE, 7
      value :SPACE_TYPE_SEQUENCE, 8
      value :SPACE_TYPE_GRAPH, 9
      value :SPACE_TYPE_IMAGE, 10
    end
    add_enum "DataType" do
      value :DATA_TYPE_UNSPECIFIED, 0
      value :DATA_TYPE_FLOAT, 1
      value :DATA_TYPE_INT, 2
      value :DATA_TYPE_BOOLEAN, 3
    end
  end
end

FloatTensor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FloatTensor").msgclass
IntTensor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IntTensor").msgclass
BoolTensor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BoolTensor").msgclass
GraphSpace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GraphSpace").msgclass
Graph = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Graph").msgclass
Image = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Image").msgclass
Space = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Space").msgclass
Data = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Data").msgclass
CompressionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CompressionType").enummodule
SpaceType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SpaceType").enummodule
DataType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DataType").enummodule
