# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: channel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gymize_pb2 as gymize__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchannel.proto\x1a\x0cgymize.proto\"P\n\x0bHeaderProto\x12\'\n\x0cmessage_type\x18\x01 \x01(\x0e\x32\x11.MessageTypeProto\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\x0c\"U\n\x0c\x43ontentProto\x12\r\n\x03raw\x18\x01 \x01(\x0cH\x00\x12\x0e\n\x04text\x18\x02 \x01(\tH\x00\x12\x1e\n\x06gymize\x18\x03 \x01(\x0b\x32\x0c.GymizeProtoH\x00\x42\x06\n\x04\x64\x61ta\"L\n\x0cMessageProto\x12\x1c\n\x06header\x18\x01 \x01(\x0b\x32\x0c.HeaderProto\x12\x1e\n\x07\x63ontent\x18\x02 \x01(\x0b\x32\r.ContentProto*\x97\x01\n\x10MessageTypeProto\x12\"\n\x1eMESSAGE_TYPE_PROTO_UNSPECIFIED\x10\x00\x12\x1e\n\x1aMESSAGE_TYPE_PROTO_MESSAGE\x10\x01\x12\x1e\n\x1aMESSAGE_TYPE_PROTO_REQUEST\x10\x02\x12\x1f\n\x1bMESSAGE_TYPE_PROTO_RESPONSE\x10\x03\x42\x12\xaa\x02\x0fGymize.Protobufb\x06proto3')

_MESSAGETYPEPROTO = DESCRIPTOR.enum_types_by_name['MessageTypeProto']
MessageTypeProto = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPEPROTO)
MESSAGE_TYPE_PROTO_UNSPECIFIED = 0
MESSAGE_TYPE_PROTO_MESSAGE = 1
MESSAGE_TYPE_PROTO_REQUEST = 2
MESSAGE_TYPE_PROTO_RESPONSE = 3


_HEADERPROTO = DESCRIPTOR.message_types_by_name['HeaderProto']
_CONTENTPROTO = DESCRIPTOR.message_types_by_name['ContentProto']
_MESSAGEPROTO = DESCRIPTOR.message_types_by_name['MessageProto']
HeaderProto = _reflection.GeneratedProtocolMessageType('HeaderProto', (_message.Message,), {
  'DESCRIPTOR' : _HEADERPROTO,
  '__module__' : 'channel_pb2'
  # @@protoc_insertion_point(class_scope:HeaderProto)
  })
_sym_db.RegisterMessage(HeaderProto)

ContentProto = _reflection.GeneratedProtocolMessageType('ContentProto', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTPROTO,
  '__module__' : 'channel_pb2'
  # @@protoc_insertion_point(class_scope:ContentProto)
  })
_sym_db.RegisterMessage(ContentProto)

MessageProto = _reflection.GeneratedProtocolMessageType('MessageProto', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEPROTO,
  '__module__' : 'channel_pb2'
  # @@protoc_insertion_point(class_scope:MessageProto)
  })
_sym_db.RegisterMessage(MessageProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017Gymize.Protobuf'
  _MESSAGETYPEPROTO._serialized_start=279
  _MESSAGETYPEPROTO._serialized_end=430
  _HEADERPROTO._serialized_start=31
  _HEADERPROTO._serialized_end=111
  _CONTENTPROTO._serialized_start=113
  _CONTENTPROTO._serialized_end=198
  _MESSAGEPROTO._serialized_start=200
  _MESSAGEPROTO._serialized_end=276
# @@protoc_insertion_point(module_scope)
