// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gymize.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gymize.Protobuf {

  /// <summary>Holder for reflection information generated from gymize.proto</summary>
  public static partial class GymizeReflection {

    #region Descriptor
    /// <summary>File descriptor for gymize.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GymizeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxneW1pemUucHJvdG8aC3NwYWNlLnByb3RvGg1sb2NhdG9yLnByb3RvGgxy",
            "ZW5kZXIucHJvdG8iPAoLQWN0aW9uUHJvdG8SDQoFYWdlbnQYASABKAkSHgoG",
            "YWN0aW9uGAIgASgLMg4uSW5zdGFuY2VQcm90byJXChBPYnNlcnZhdGlvblBy",
            "b3RvEh4KB2xvY2F0b3IYASABKAsyDS5Mb2NhdG9yUHJvdG8SIwoLb2JzZXJ2",
            "YXRpb24YAiABKAsyDi5JbnN0YW5jZVByb3RvIiwKC1Jld2FyZFByb3RvEg0K",
            "BWFnZW50GAEgASgJEg4KBnJld2FyZBgCIAEoASI5CglJbmZvUHJvdG8SDQoF",
            "YWdlbnQYASABKAkSHQoFaW5mb3MYAiADKAsyDi5JbnN0YW5jZVByb3RvIqwC",
            "CgtHeW1pemVQcm90bxIUCgxyZXNldF9hZ2VudHMYASADKAkSFgoOcmVxdWVz",
            "dF9hZ2VudHMYAiADKAkSFwoPcmVzcG9uc2VfYWdlbnRzGAMgAygJEh0KB2Fj",
            "dGlvbnMYBCADKAsyDC5BY3Rpb25Qcm90bxInCgxvYnNlcnZhdGlvbnMYBSAD",
            "KAsyES5PYnNlcnZhdGlvblByb3RvEh0KB3Jld2FyZHMYBiADKAsyDC5SZXdh",
            "cmRQcm90bxIZChF0ZXJtaW5hdGVkX2FnZW50cxgHIAMoCRIYChB0cnVuY2F0",
            "ZWRfYWdlbnRzGAggAygJEhkKBWluZm9zGAkgAygLMgouSW5mb1Byb3RvEh8K",
            "CXJlbmRlcmluZxgKIAEoCzIMLlJlbmRlclByb3RvQhKqAg9HeW1pemUuUHJv",
            "dG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gymize.Protobuf.SpaceReflection.Descriptor, global::Gymize.Protobuf.LocatorReflection.Descriptor, global::Gymize.Protobuf.RenderReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Gymize.Protobuf.ActionProto), global::Gymize.Protobuf.ActionProto.Parser, new[]{ "Agent", "Action" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gymize.Protobuf.ObservationProto), global::Gymize.Protobuf.ObservationProto.Parser, new[]{ "Locator", "Observation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gymize.Protobuf.RewardProto), global::Gymize.Protobuf.RewardProto.Parser, new[]{ "Agent", "Reward" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gymize.Protobuf.InfoProto), global::Gymize.Protobuf.InfoProto.Parser, new[]{ "Agent", "Infos" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gymize.Protobuf.GymizeProto), global::Gymize.Protobuf.GymizeProto.Parser, new[]{ "ResetAgents", "RequestAgents", "ResponseAgents", "Actions", "Observations", "Rewards", "TerminatedAgents", "TruncatedAgents", "Infos", "Rendering" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ActionProto : pb::IMessage<ActionProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionProto> _parser = new pb::MessageParser<ActionProto>(() => new ActionProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActionProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gymize.Protobuf.GymizeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionProto(ActionProto other) : this() {
      agent_ = other.agent_;
      action_ = other.action_ != null ? other.action_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionProto Clone() {
      return new ActionProto(this);
    }

    /// <summary>Field number for the "agent" field.</summary>
    public const int AgentFieldNumber = 1;
    private string agent_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Agent {
      get { return agent_; }
      set {
        agent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 2;
    private global::Gymize.Protobuf.InstanceProto action_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Gymize.Protobuf.InstanceProto Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActionProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActionProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Agent != other.Agent) return false;
      if (!object.Equals(Action, other.Action)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Agent.Length != 0) hash ^= Agent.GetHashCode();
      if (action_ != null) hash ^= Action.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Agent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Agent);
      }
      if (action_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Action);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Agent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Agent);
      }
      if (action_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Action);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Agent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Agent);
      }
      if (action_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Action);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActionProto other) {
      if (other == null) {
        return;
      }
      if (other.Agent.Length != 0) {
        Agent = other.Agent;
      }
      if (other.action_ != null) {
        if (action_ == null) {
          Action = new global::Gymize.Protobuf.InstanceProto();
        }
        Action.MergeFrom(other.Action);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Agent = input.ReadString();
            break;
          }
          case 18: {
            if (action_ == null) {
              Action = new global::Gymize.Protobuf.InstanceProto();
            }
            input.ReadMessage(Action);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Agent = input.ReadString();
            break;
          }
          case 18: {
            if (action_ == null) {
              Action = new global::Gymize.Protobuf.InstanceProto();
            }
            input.ReadMessage(Action);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ObservationProto : pb::IMessage<ObservationProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ObservationProto> _parser = new pb::MessageParser<ObservationProto>(() => new ObservationProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ObservationProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gymize.Protobuf.GymizeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ObservationProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ObservationProto(ObservationProto other) : this() {
      locator_ = other.locator_ != null ? other.locator_.Clone() : null;
      observation_ = other.observation_ != null ? other.observation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ObservationProto Clone() {
      return new ObservationProto(this);
    }

    /// <summary>Field number for the "locator" field.</summary>
    public const int LocatorFieldNumber = 1;
    private global::Gymize.Protobuf.LocatorProto locator_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Gymize.Protobuf.LocatorProto Locator {
      get { return locator_; }
      set {
        locator_ = value;
      }
    }

    /// <summary>Field number for the "observation" field.</summary>
    public const int ObservationFieldNumber = 2;
    private global::Gymize.Protobuf.InstanceProto observation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Gymize.Protobuf.InstanceProto Observation {
      get { return observation_; }
      set {
        observation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ObservationProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ObservationProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Locator, other.Locator)) return false;
      if (!object.Equals(Observation, other.Observation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (locator_ != null) hash ^= Locator.GetHashCode();
      if (observation_ != null) hash ^= Observation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (locator_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Locator);
      }
      if (observation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Observation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (locator_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Locator);
      }
      if (observation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Observation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (locator_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Locator);
      }
      if (observation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Observation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ObservationProto other) {
      if (other == null) {
        return;
      }
      if (other.locator_ != null) {
        if (locator_ == null) {
          Locator = new global::Gymize.Protobuf.LocatorProto();
        }
        Locator.MergeFrom(other.Locator);
      }
      if (other.observation_ != null) {
        if (observation_ == null) {
          Observation = new global::Gymize.Protobuf.InstanceProto();
        }
        Observation.MergeFrom(other.Observation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (locator_ == null) {
              Locator = new global::Gymize.Protobuf.LocatorProto();
            }
            input.ReadMessage(Locator);
            break;
          }
          case 18: {
            if (observation_ == null) {
              Observation = new global::Gymize.Protobuf.InstanceProto();
            }
            input.ReadMessage(Observation);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (locator_ == null) {
              Locator = new global::Gymize.Protobuf.LocatorProto();
            }
            input.ReadMessage(Locator);
            break;
          }
          case 18: {
            if (observation_ == null) {
              Observation = new global::Gymize.Protobuf.InstanceProto();
            }
            input.ReadMessage(Observation);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RewardProto : pb::IMessage<RewardProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RewardProto> _parser = new pb::MessageParser<RewardProto>(() => new RewardProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RewardProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gymize.Protobuf.GymizeReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RewardProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RewardProto(RewardProto other) : this() {
      agent_ = other.agent_;
      reward_ = other.reward_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RewardProto Clone() {
      return new RewardProto(this);
    }

    /// <summary>Field number for the "agent" field.</summary>
    public const int AgentFieldNumber = 1;
    private string agent_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Agent {
      get { return agent_; }
      set {
        agent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reward" field.</summary>
    public const int RewardFieldNumber = 2;
    private double reward_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Reward {
      get { return reward_; }
      set {
        reward_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RewardProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RewardProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Agent != other.Agent) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Reward, other.Reward)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Agent.Length != 0) hash ^= Agent.GetHashCode();
      if (Reward != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Reward);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Agent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Agent);
      }
      if (Reward != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Reward);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Agent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Agent);
      }
      if (Reward != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Reward);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Agent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Agent);
      }
      if (Reward != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RewardProto other) {
      if (other == null) {
        return;
      }
      if (other.Agent.Length != 0) {
        Agent = other.Agent;
      }
      if (other.Reward != 0D) {
        Reward = other.Reward;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Agent = input.ReadString();
            break;
          }
          case 17: {
            Reward = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Agent = input.ReadString();
            break;
          }
          case 17: {
            Reward = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class InfoProto : pb::IMessage<InfoProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InfoProto> _parser = new pb::MessageParser<InfoProto>(() => new InfoProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InfoProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gymize.Protobuf.GymizeReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InfoProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InfoProto(InfoProto other) : this() {
      agent_ = other.agent_;
      infos_ = other.infos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InfoProto Clone() {
      return new InfoProto(this);
    }

    /// <summary>Field number for the "agent" field.</summary>
    public const int AgentFieldNumber = 1;
    private string agent_ = "";
    /// <summary>
    /// "" for env info
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Agent {
      get { return agent_; }
      set {
        agent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Gymize.Protobuf.InstanceProto> _repeated_infos_codec
        = pb::FieldCodec.ForMessage(18, global::Gymize.Protobuf.InstanceProto.Parser);
    private readonly pbc::RepeatedField<global::Gymize.Protobuf.InstanceProto> infos_ = new pbc::RepeatedField<global::Gymize.Protobuf.InstanceProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Gymize.Protobuf.InstanceProto> Infos {
      get { return infos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InfoProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InfoProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Agent != other.Agent) return false;
      if(!infos_.Equals(other.infos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Agent.Length != 0) hash ^= Agent.GetHashCode();
      hash ^= infos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Agent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Agent);
      }
      infos_.WriteTo(output, _repeated_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Agent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Agent);
      }
      infos_.WriteTo(ref output, _repeated_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Agent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Agent);
      }
      size += infos_.CalculateSize(_repeated_infos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InfoProto other) {
      if (other == null) {
        return;
      }
      if (other.Agent.Length != 0) {
        Agent = other.Agent;
      }
      infos_.Add(other.infos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Agent = input.ReadString();
            break;
          }
          case 18: {
            infos_.AddEntriesFrom(input, _repeated_infos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Agent = input.ReadString();
            break;
          }
          case 18: {
            infos_.AddEntriesFrom(ref input, _repeated_infos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GymizeProto : pb::IMessage<GymizeProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GymizeProto> _parser = new pb::MessageParser<GymizeProto>(() => new GymizeProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GymizeProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gymize.Protobuf.GymizeReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GymizeProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GymizeProto(GymizeProto other) : this() {
      resetAgents_ = other.resetAgents_.Clone();
      requestAgents_ = other.requestAgents_.Clone();
      responseAgents_ = other.responseAgents_.Clone();
      actions_ = other.actions_.Clone();
      observations_ = other.observations_.Clone();
      rewards_ = other.rewards_.Clone();
      terminatedAgents_ = other.terminatedAgents_.Clone();
      truncatedAgents_ = other.truncatedAgents_.Clone();
      infos_ = other.infos_.Clone();
      rendering_ = other.rendering_ != null ? other.rendering_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GymizeProto Clone() {
      return new GymizeProto(this);
    }

    /// <summary>Field number for the "reset_agents" field.</summary>
    public const int ResetAgentsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_resetAgents_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> resetAgents_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// "" for the environment, others for individual agents
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ResetAgents {
      get { return resetAgents_; }
    }

    /// <summary>Field number for the "request_agents" field.</summary>
    public const int RequestAgentsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_requestAgents_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> requestAgents_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// ask for observations, rewards, infos or actions belong to agent name, "" will clear env info
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> RequestAgents {
      get { return requestAgents_; }
    }

    /// <summary>Field number for the "response_agents" field.</summary>
    public const int ResponseAgentsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_responseAgents_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> responseAgents_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// agents that response to the request_agents
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ResponseAgents {
      get { return responseAgents_; }
    }

    /// <summary>Field number for the "actions" field.</summary>
    public const int ActionsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Gymize.Protobuf.ActionProto> _repeated_actions_codec
        = pb::FieldCodec.ForMessage(34, global::Gymize.Protobuf.ActionProto.Parser);
    private readonly pbc::RepeatedField<global::Gymize.Protobuf.ActionProto> actions_ = new pbc::RepeatedField<global::Gymize.Protobuf.ActionProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Gymize.Protobuf.ActionProto> Actions {
      get { return actions_; }
    }

    /// <summary>Field number for the "observations" field.</summary>
    public const int ObservationsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Gymize.Protobuf.ObservationProto> _repeated_observations_codec
        = pb::FieldCodec.ForMessage(42, global::Gymize.Protobuf.ObservationProto.Parser);
    private readonly pbc::RepeatedField<global::Gymize.Protobuf.ObservationProto> observations_ = new pbc::RepeatedField<global::Gymize.Protobuf.ObservationProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Gymize.Protobuf.ObservationProto> Observations {
      get { return observations_; }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Gymize.Protobuf.RewardProto> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(50, global::Gymize.Protobuf.RewardProto.Parser);
    private readonly pbc::RepeatedField<global::Gymize.Protobuf.RewardProto> rewards_ = new pbc::RepeatedField<global::Gymize.Protobuf.RewardProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Gymize.Protobuf.RewardProto> Rewards {
      get { return rewards_; }
    }

    /// <summary>Field number for the "terminated_agents" field.</summary>
    public const int TerminatedAgentsFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_terminatedAgents_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> terminatedAgents_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// "" for the environment, others for individual agents
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> TerminatedAgents {
      get { return terminatedAgents_; }
    }

    /// <summary>Field number for the "truncated_agents" field.</summary>
    public const int TruncatedAgentsFieldNumber = 8;
    private static readonly pb::FieldCodec<string> _repeated_truncatedAgents_codec
        = pb::FieldCodec.ForString(66);
    private readonly pbc::RepeatedField<string> truncatedAgents_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// "" for the environment, others for individual agents
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> TruncatedAgents {
      get { return truncatedAgents_; }
    }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Gymize.Protobuf.InfoProto> _repeated_infos_codec
        = pb::FieldCodec.ForMessage(74, global::Gymize.Protobuf.InfoProto.Parser);
    private readonly pbc::RepeatedField<global::Gymize.Protobuf.InfoProto> infos_ = new pbc::RepeatedField<global::Gymize.Protobuf.InfoProto>();
    /// <summary>
    /// can go with observations but do not need to go with actions
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Gymize.Protobuf.InfoProto> Infos {
      get { return infos_; }
    }

    /// <summary>Field number for the "rendering" field.</summary>
    public const int RenderingFieldNumber = 10;
    private global::Gymize.Protobuf.RenderProto rendering_;
    /// <summary>
    /// render images and audio
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Gymize.Protobuf.RenderProto Rendering {
      get { return rendering_; }
      set {
        rendering_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GymizeProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GymizeProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!resetAgents_.Equals(other.resetAgents_)) return false;
      if(!requestAgents_.Equals(other.requestAgents_)) return false;
      if(!responseAgents_.Equals(other.responseAgents_)) return false;
      if(!actions_.Equals(other.actions_)) return false;
      if(!observations_.Equals(other.observations_)) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      if(!terminatedAgents_.Equals(other.terminatedAgents_)) return false;
      if(!truncatedAgents_.Equals(other.truncatedAgents_)) return false;
      if(!infos_.Equals(other.infos_)) return false;
      if (!object.Equals(Rendering, other.Rendering)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= resetAgents_.GetHashCode();
      hash ^= requestAgents_.GetHashCode();
      hash ^= responseAgents_.GetHashCode();
      hash ^= actions_.GetHashCode();
      hash ^= observations_.GetHashCode();
      hash ^= rewards_.GetHashCode();
      hash ^= terminatedAgents_.GetHashCode();
      hash ^= truncatedAgents_.GetHashCode();
      hash ^= infos_.GetHashCode();
      if (rendering_ != null) hash ^= Rendering.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      resetAgents_.WriteTo(output, _repeated_resetAgents_codec);
      requestAgents_.WriteTo(output, _repeated_requestAgents_codec);
      responseAgents_.WriteTo(output, _repeated_responseAgents_codec);
      actions_.WriteTo(output, _repeated_actions_codec);
      observations_.WriteTo(output, _repeated_observations_codec);
      rewards_.WriteTo(output, _repeated_rewards_codec);
      terminatedAgents_.WriteTo(output, _repeated_terminatedAgents_codec);
      truncatedAgents_.WriteTo(output, _repeated_truncatedAgents_codec);
      infos_.WriteTo(output, _repeated_infos_codec);
      if (rendering_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Rendering);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      resetAgents_.WriteTo(ref output, _repeated_resetAgents_codec);
      requestAgents_.WriteTo(ref output, _repeated_requestAgents_codec);
      responseAgents_.WriteTo(ref output, _repeated_responseAgents_codec);
      actions_.WriteTo(ref output, _repeated_actions_codec);
      observations_.WriteTo(ref output, _repeated_observations_codec);
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      terminatedAgents_.WriteTo(ref output, _repeated_terminatedAgents_codec);
      truncatedAgents_.WriteTo(ref output, _repeated_truncatedAgents_codec);
      infos_.WriteTo(ref output, _repeated_infos_codec);
      if (rendering_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Rendering);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += resetAgents_.CalculateSize(_repeated_resetAgents_codec);
      size += requestAgents_.CalculateSize(_repeated_requestAgents_codec);
      size += responseAgents_.CalculateSize(_repeated_responseAgents_codec);
      size += actions_.CalculateSize(_repeated_actions_codec);
      size += observations_.CalculateSize(_repeated_observations_codec);
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      size += terminatedAgents_.CalculateSize(_repeated_terminatedAgents_codec);
      size += truncatedAgents_.CalculateSize(_repeated_truncatedAgents_codec);
      size += infos_.CalculateSize(_repeated_infos_codec);
      if (rendering_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rendering);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GymizeProto other) {
      if (other == null) {
        return;
      }
      resetAgents_.Add(other.resetAgents_);
      requestAgents_.Add(other.requestAgents_);
      responseAgents_.Add(other.responseAgents_);
      actions_.Add(other.actions_);
      observations_.Add(other.observations_);
      rewards_.Add(other.rewards_);
      terminatedAgents_.Add(other.terminatedAgents_);
      truncatedAgents_.Add(other.truncatedAgents_);
      infos_.Add(other.infos_);
      if (other.rendering_ != null) {
        if (rendering_ == null) {
          Rendering = new global::Gymize.Protobuf.RenderProto();
        }
        Rendering.MergeFrom(other.Rendering);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            resetAgents_.AddEntriesFrom(input, _repeated_resetAgents_codec);
            break;
          }
          case 18: {
            requestAgents_.AddEntriesFrom(input, _repeated_requestAgents_codec);
            break;
          }
          case 26: {
            responseAgents_.AddEntriesFrom(input, _repeated_responseAgents_codec);
            break;
          }
          case 34: {
            actions_.AddEntriesFrom(input, _repeated_actions_codec);
            break;
          }
          case 42: {
            observations_.AddEntriesFrom(input, _repeated_observations_codec);
            break;
          }
          case 50: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
          case 58: {
            terminatedAgents_.AddEntriesFrom(input, _repeated_terminatedAgents_codec);
            break;
          }
          case 66: {
            truncatedAgents_.AddEntriesFrom(input, _repeated_truncatedAgents_codec);
            break;
          }
          case 74: {
            infos_.AddEntriesFrom(input, _repeated_infos_codec);
            break;
          }
          case 82: {
            if (rendering_ == null) {
              Rendering = new global::Gymize.Protobuf.RenderProto();
            }
            input.ReadMessage(Rendering);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            resetAgents_.AddEntriesFrom(ref input, _repeated_resetAgents_codec);
            break;
          }
          case 18: {
            requestAgents_.AddEntriesFrom(ref input, _repeated_requestAgents_codec);
            break;
          }
          case 26: {
            responseAgents_.AddEntriesFrom(ref input, _repeated_responseAgents_codec);
            break;
          }
          case 34: {
            actions_.AddEntriesFrom(ref input, _repeated_actions_codec);
            break;
          }
          case 42: {
            observations_.AddEntriesFrom(ref input, _repeated_observations_codec);
            break;
          }
          case 50: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
          case 58: {
            terminatedAgents_.AddEntriesFrom(ref input, _repeated_terminatedAgents_codec);
            break;
          }
          case 66: {
            truncatedAgents_.AddEntriesFrom(ref input, _repeated_truncatedAgents_codec);
            break;
          }
          case 74: {
            infos_.AddEntriesFrom(ref input, _repeated_infos_codec);
            break;
          }
          case 82: {
            if (rendering_ == null) {
              Rendering = new global::Gymize.Protobuf.RenderProto();
            }
            input.ReadMessage(Rendering);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
